# tag_grouping.py

tag_categories = {
    "Emotions": {
        "Positive Emotions": [
            "joy",
            "gratitude",
            "happiness",
            "contentment",
            "excitement",
            "hopefulness",
            "optimism",
            "love",
            "love declaration",
            "love expression",
            "love and appreciation",
            "love and affection",
            "love and devotion",
            "positive self-image",
            "self-confidence",
            "self-esteem",
            "confidence",
            "determination",
            "resilience",
            "self-empowerment",
            "self-awareness",
            "self-reflection",
            "self-disclosure",
            "self-improvement",
            "self-forgiveness",
            "self-care",
            "self-acceptance",
            "positive outlook",
            "positive intention",
            "positive engagement",
            "positive sentiment",
            "positive connection",
            "positive affirmation",
            "positive self-expression",
            "positive reinforcement",
            "positive response",
            "positive suggestions",
            "positive wellbeing",
            "support",
            "supportive friendship",
            "supportive relationship",
            "supportive message",
            "encouragement",
            "reassurance",
            "affirmation",
            "affirming support"
        ],
        "Negative Emotions": [
            "anger",
            "frustration",
            "sadness",
            "fear",
            "anxiety",
            "jealousy",
            "disappointment",
            "disgust",
            "resentment",
            "overwhelm",
            "stress",
            "self-doubt",
            "self-criticism",
            "self-deprecation",
            "negativity",
            "negative emotions",
            "negative perception",
            "negative feelings",
            "negative response",
            "anger/frustration",
            "emotional distress",
            "emotional burden",
            "emotional insecurity",
            "emotional struggle",
            "emotional impact",
            "emotional confusion",
            "emotional disconnect",
            "emotional plea",
            "emotional depth",
            "emotional complexity",
            "emotional anguish",
            "emotional pain",
            "emotional exhaustion",
            "emotional turmoil",
            "emotional conflict",
            "emotional discomfort",
            "emotional dissatisfaction"
        ],
        "Mixed Emotions": [
            "mixed feelings",
            "ambivalence",
            "confusion",
            "curiosity",
            "wonder",
            "intrigue",
            "reflection",
            "self-awareness",
            "self-reflection"
        ],
        "Neutral Emotions": [
            "calm",
            "relaxation",
            "contentment",
            "acceptance",
            "comfort",
            "neutral opinion",
            "neutral",
            "neutral sentiment",
            "general mood",
            "unconditional love",
            "relaxed mood",
            "relaxed"
        ]
    },
    "Relationship Dynamics": {
        "Positive Relationships": [
            "friendship",
            "companionship",
            "partnership",
            "trust",
            "trust building",
            "mutual feelings",
            "reciprocal relationships",
            "relationship bonding",
            "relationship appreciation",
            "relationship realization",
            "relationship reflection",
            "relationship improvement",
            "relationship commitment",
            "supportive friendship",
            "supportive relationship",
            "support"
        ],
        "Negative Relationships": [
            "infidelity",
            "betrayal",
            "relationship conflict",
            "relationship challenges",
            "relationship issues",
            "relationship distress",
            "relationship struggles",
            "relationship turmoil",
            "relationship concern"
        ],
        "Unclear Relationships": [
            "ambiguous relationship",
            "relationship uncertainty",
            "relationship status",
            "unclear communication"
        ]
    },
    "Interaction Styles": {
        "Playful": [
            "playful",
            "playful intent",
            "playful mood",
            "playful expression",
            "playful teasing",
            "playful tone",
            "playful interaction",
            "playful tease"
        ],
        "Flirty": [
            "flirty",
            "flirtatious",
            "flirtation"
        ],
        "Humorous": [
            "sarcasm",
            "humorous",
            "humor",
            "sarcastic",
            "banter",
            "teasing",
            "humorous frustration",
            "humorous resignation",
            "humorous discomfort",
            "humorous relief",
            "humorous irritation",
            "dark humor",
            "humor request",
            "humor amidst struggle"
        ],
        "Supportive": [
            "supportive",
            "supportive friendship",
            "supportive message",
            "support",
            "supportive relationship",
            "supportive response",
            "encouragement",
            "reassurance",
            "affirmation",
            "affirming support"
        ],
        "Aggressive": [
            "aggression",
            "aggressive confrontation",
            "aggressive intent",
            "defensiveness",
            "defiance"
        ],
        "Defiant": [
            "defiance",
            "defensiveness"
        ]
    },
    "Topics & Activities": {
        "Work & Career": [
            "work",
            "workout motivation",
            "work project",
            "work-related stress",
            "work environment",
            "work discussion",
            "work stress",
            "workaholic tendencies",
            "workload",
            "work routine",
            "work-related"
        ],
        "Health & Well-being": [
            "health",
            "mental health",
            "mental well-being",
            "mental health awareness",
            "health concerns",
            "health concern",
            "health issues",
            "physical discomfort",
            "digestive issues",
            "sleep troubles",
            "sleep issues",
            "insomnia",
            "digestion issues",
            "digestion health",
            "fatigue",
            "tiredness",
            "exhaustion",
            "stressful experience"
        ],
        "Leisure & Hobbies": [
            "leisure activities",
            "gaming",
            "gaming frustration",
            "game suggestion",
            "game rules",
            "game night",
            "game invitation",
            "game playing",
            "playtime",
            "recreation",
            "fun activities",
            "adventure",
            "adventures",
            "recreational interests",
            "gardening",
            "travel",
            "cooking and food"
        ],
        "Technology & Science": [
            "technology",
            "technical issues",
            "technical support",
            "technical difficulty",
            "technology troubleshooting",
            "technology excitement",
            "technology improvement",
            "technology repair",
            "technology discussions",
            "technical assistance",
            "technical achievement",
            "technical success"
        ],
        "Family & Parenting": [
            "parenting",
            "parent-child relationship",
            "parenting struggles",
            "parenting concerns",
            "parenthood",
            "family bond",
            "family activities",
            "caregiving",
            "family support",
            "marital issues",
            "parenting challenges"
        ],
        "Spirituality & Philosophy": [
            "spirituality",
            "spiritual support",
            "spiritual reflection",
            "religious devotion",
            "religious debate",
            "philosophy",
            "philosophical reflection",
            "philosophical discussion",
            "moral reasoning",
            "life philosophy"
        ],
        "Social & Communication": [
            "social media",
            "social interaction",
            "social engagement",
            "social invitation",
            "social challenges",
            "social activity"
        ],
        "Personal Development": [
            "self-improvement",
            "personal growth",
            "self-awareness",
            "self-esteem",
            "self-confidence",
            "self-reflection",
            "self-empowerment",
            "self-forgiveness",
            "self-disclosure",
            "self-criticism",
            "self-identity",
            "self-preservation",
            "self-care",
            "self-acceptance"
        ]
    },
    "Intentions & Behaviors": {
        "Seeking Support & Help": [
            "seeking support",
            "seeking help",
            "seeking suggestions",
            "seeking validation",
            "seeking clarity",
            "seeking understanding",
            "seeking reassurance",
            "seeking engagement",
            "seeking alternatives",
            "seeking guidance",
            "seeking information",
            "seeking forgiveness",
            "seeking empathy",
            "seeking permission",
            "seeking solutions",
            "seeking assistance"
        ],
        "Requests & Suggestions": [
            "request for help",
            "request for engagement",
            "request for clarification",
            "request for prayer",
            "request for brevity",
            "request for sincerity",
            "request for feedback",
            "suggestion",
            "suggestion for intimacy",
            "suggestion for play",
            "suggestion for activity",
            "suggestion needed",
            "suggestions",
            "suggestive language",
            "suggestion for intimacy",
            "suggestive",
            "suggestive language",
            "suggestion for play",
            "suggestion for activity",
            "suggestion needed",
            "suggestions",
            "suggestive language",
            "suggestions needed"
        ],
        "Complaints & Criticism": [
            "complaint",
            "criticisms",
            "negative feedback",
            "negative perception",
            "negative experience",
            "negative treatment",
            "medication criticism",
            "criticism",
            "self-criticism",
            "negative emotions",
            "negative feelings",
            "negative response",
            "disapproval",
            "defensiveness",
            "defiance",
            "aggression",
            "aggressive confrontation",
            "aggressive intent",
            "provocation",
            "provocative language",
            "provocative comment",
            "provocative suggestion",
            "provocative question",
            "provocative behavior",
            "provocative statement"
        ],
        "Affirmations & Encouragement": [
            "affirmation",
            "affirming support",
            "supportive message",
            "support",
            "supportive friendship",
            "supportive relationship",
            "encouragement",
            "reassurance"
        ]
    },
    "Values & Ethics": {
        "Moral Values": [
            "moral reasoning",
            "moral dilemma",
            "moral perspective",
            "moral values",
            "moral struggle",
            "moral confusion"
        ],
        "Ethical Values": [
            "ethical dilemma",
            "ethical values",
            "ethical reasoning",
            "ethical considerations"
        ],
        "Religious & Spiritual Values": [
            "religious devotion",
            "spiritual reflection",
            "spiritual support",
            "religious debate",
            "life philosophy"
        ]
    },
    "Sexual & Explicit Content": {
        "Sexual Desires & Expressions": [
            "sexual desire",
            "sexual humor",
            "sexual expression",
            "sexual innuendo",
            "sexual arousal",
            "sexual content",
            "sexual tension",
            "sexual advances",
            "sexual confidence",
            "sexual intimacy discussion",
            "sexual struggles",
            "sexual harassment",
            "sexual excitement",
            "sexual dissatisfaction",
            "sexual suggestion"
        ],
        "Vulgar & Explicit Language": [
            "explicit",
            "vulgar language",
            "vulgarity",
            "offensive language",
            "inappropriate language",
            "inappropriate suggestion",
            "inappropriate humor",
            "sexually explicit",
            "sexually suggestive",
            "inappropriate conversation",
            "provocative language",
            "provocative comment",
            "provocative statement",
            "provocative behavior"
        ],
        "Sexual Relationships & Issues": [
            "romantic relationships",
            "sexual frustration",
            "infidelity",
            "relationship turmoil",
            "sexual harassment",
            "sexual struggles",
            "romantic trust",
            "romantic flirtation",
            "romantic intent",
            "romantic commitment",
            "romantic desire",
            "romantic affection"
        ]
    },
    "Miscellaneous": {
        "Others": [
            "AI",
            "swagger",
            "robot activities",
            "objectification",
            "data training",
            "device troubleshooting",
            "texture application",
            "relational strain",
            "attachment issues",
            "weather concerns",
            "financial saving",
            "financial security",
            "safety concerns",
            "property investment",
            "property discussion"
        ]
    }
}
