# tag_grouping.py

tag_categories = {
    "Emotions": {
        "Positive Emotions": [
            "joyful response",
            "adoration",
            "determination",
            "support",
            "supportive relationship",
            "positive sentiment",
            "love and appreciation",
            "affection",
            "warm",
            "positive suggestions",
            "gratitude",
            "positive response",
            "positive self-image",
            "positive self-expression",
            "positive connection",
            "hopefulness",
            "confidence",
            "expressing affection",
            "love and devotion",
            "self-esteem",
            "happiness",
            "self-acceptance",
            "supportive message",
            "hope",
            "positive outlook",
            "joy",
            "positive affirmation",
            "appreciation",
            "self-care",
            "self-empowerment",
            "positive engagement",
            "expressing love",
            "positive intention",
            "self-awareness",
            "self-forgiveness",
            "self-disclosure",
            "resilience",
            "positive wellbeing",
            "contentment",
            "self-reflection",
            "excitement",
            "reassurance",
            "expressing excitement",
            "affirming support",
            "positive reinforcement",
            "self-confidence",
            "love declaration",
            "supportive friendship",
            "optimism",
            "love",
            "self-improvement",
            "love expression",
            "expressing gratitude",
            "encouragement",
            "affirmation",
            "love and affection"
        ],
        "Negative Emotions": [
            "self-deprecation",
            "emotional burden",
            "emotional insecurity",
            "sadness",
            "emotional struggle",
            "desperation",
            "emotional confusion",
            "self-doubt",
            "emotional plea",
            "emotional distress",
            "emotional complexity",
            "feeling unsafe",
            "stress",
            "expressing frustration",
            "expressing dissatisfaction",
            "anger",
            "emotional dissatisfaction",
            "disappointment",
            "despair",
            "emotional pain",
            "depression",
            "expressing sorrow",
            "emotional turmoil",
            "emotional impact",
            "negative response",
            "disgust",
            "negative feelings",
            "emotional conflict",
            "emotional exhaustion",
            "emotional depth",
            "resentment",
            "anxiety",
            "negative perception",
            "self-criticism",
            "emotional discomfort",
            "jealousy",
            "negative emotions",
            "overwhelm",
            "emotional vulnerability",
            "frustration",
            "fear",
            "feeling broken",
            "feeling discouraged",
            "anger/frustration",
            "emotional disconnect",
            "feeling unhappy",
            "emotional anguish",
            "negativity"
        ],
        "Mixed Emotions": [
            "expressing opinions",
            "expressing doubt",
            "confusion",
            "ambivalence",
            "self-awareness",
            "uncertainty",
            "wonder",
            "curiosity",
            "doubt",
            "self-reflection",
            "mixed emotions",
            "reflection",
            "mixed feelings",
            "intrigue"
        ],
        "Neutral Emotions": [
            "unconditional love",
            "neutral sentiment",
            "relaxation",
            "relaxed mood",
            "neutral opinion",
            "general mood",
            "relaxed",
            "neutral",
            "calm",
            "comfort",
            "contentment",
            "acceptance"
        ]
    },
    "Relationship Dynamics": {
        "Positive Relationships": [
            "trust building",
            "relationship improvement",
            "support",
            "supportive relationship",
            "friendship",
            "expressing interest",
            "relationship building",
            "relationship realization",
            "companionship",
            "relationship reflection",
            "reciprocal relationships",
            "relationship commitment",
            "trust",
            "partnership",
            "supportive friendship",
            "romantic response",
            "mutual feelings",
            "relationship bonding",
            "relationship appreciation"
        ],
        "Negative Relationships": [
            "relationship tension",
            "relationship conflict",
            "relationship concern",
            "breakup",
            "relationship turmoil",
            "relationship struggles",
            "relationship challenges",
            "infidelity",
            "disappointment in relationships",
            "betrayal",
            "relationship issues",
            "relationship distress"
        ],
        "Unclear Relationships": [
            "relationship uncertainty",
            "relationship status",
            "ambiguous relationship",
            "unclear communication"
        ]
    },
    "Interaction Styles": {
        "Playful": [
            "playful teasing",
            "playful tease",
            "playful",
            "playful response",
            "playful tone",
            "playful interaction",
            "playful mood",
            "playful banter",
            "playfulness",
            "playful intent",
            "playful expression"
        ],
        "Flirty": [
            "flirting",
            "flirtatious",
            "flirtation",
            "flirting back",
            "flirty",
            "flirtatious response"
        ],
        "Humorous": [
            "humorous resignation",
            "humorous irritation",
            "humor amidst struggle",
            "humorous frustration",
            "humorous",
            "humorous relief",
            "humorous response",
            "humor",
            "dark humor",
            "humor request",
            "sarcasm",
            "humorous tone",
            "humorous discomfort",
            "banter",
            "sarcastic",
            "teasing"
        ],
        "Supportive": [
            "affirming support",
            "providing emotional support",
            "supportive friendship",
            "supportive response",
            "support",
            "supportive relationship",
            "expressing empathy",
            "supportive message",
            "giving advice",
            "supportive",
            "encouragement",
            "affirmation",
            "reassurance"
        ],
        "Aggressive": [
            "accusation",
            "aggressive tone",
            "threatening language",
            "aggressive intent",
            "threatening",
            "provocation",
            "aggressive confrontation",
            "aggression",
            "defiance",
            "defensiveness"
        ],
        "Defiant": [
            "defiance",
            "asserting dominance",
            "defensiveness"
        ]
    },
    "Topics & Activities": {
        "Work & Career": [
            "work project",
            "career focus",
            "workaholic tendencies",
            "work-related stress",
            "satisfaction with work",
            "work stress",
            "work routine",
            "work-related",
            "work discussion",
            "workout motivation",
            "work environment",
            "work",
            "workload",
            "work relationships"
        ],
        "Health & Well-being": [
            "fatigue",
            "expressing discomfort",
            "sleep issues",
            "stress",
            "digestive issues",
            "health concerns",
            "self-care advice",
            "digestion issues",
            "sleep troubles",
            "stressful experience",
            "health issues",
            "mental health support",
            "health",
            "mental health",
            "physical discomfort",
            "mental well-being",
            "tiredness",
            "exhaustion",
            "mental health awareness",
            "health concern",
            "digestion health",
            "insomnia"
        ],
        "Leisure & Hobbies": [
            "anime interest",
            "gaming",
            "travel",
            "playtime",
            "recreation",
            "hobby interest",
            "adventure",
            "cooking",
            "game suggestion",
            "adventures",
            "music interest",
            "anime",
            "fun activities",
            "game rules",
            "gaming frustration",
            "game night",
            "gardening",
            "anime discussion",
            "game playing",
            "cooking and food",
            "leisure activities",
            "recreational interests",
            "game invitation"
        ],
        "Technology & Science": [
            "technology troubleshooting",
            "technology repair",
            "technology",
            "technical success",
            "technical assistance",
            "technology discussions",
            "technical issues",
            "technology excitement",
            "technical support",
            "technical achievement",
            "future technology",
            "AI",
            "technical difficulty",
            "future speculation",
            "anticipating technology",
            "technology improvement"
        ],
        "Family & Parenting": [
            "parenthood",
            "parenting concerns",
            "family planning",
            "family bond",
            "caregiving",
            "parenting difficulties",
            "mentioning family love",
            "parenting struggles",
            "family support",
            "parenting challenges",
            "parenting",
            "family activities",
            "family",
            "parent-child relationship",
            "marital issues"
        ],
        "Spirituality & Philosophy": [
            "spirituality",
            "spiritual",
            "religious uncertainty",
            "philosophy",
            "spiritual support",
            "philosophical reflection",
            "religious beliefs",
            "moral reasoning",
            "religious devotion",
            "life philosophy",
            "spiritual reflection",
            "religious debate",
            "philosophical discussion"
        ],
        "Social & Communication": [
            "social activity",
            "social invitation",
            "social media",
            "social challenges",
            "engaging in conversation",
            "social engagement",
            "social anxiety",
            "engagement",
            "social interaction"
        ],
        "Personal Development": [
            "personal growth",
            "self-care reminder",
            "self-confidence",
            "self-preservation",
            "self-identity",
            "self-awareness",
            "self-esteem",
            "self-acceptance",
            "self-improvement",
            "self-forgiveness",
            "self-disclosure",
            "self-worth",
            "self-discovery",
            "self-care",
            "self-reflection",
            "self-empowerment",
            "personal change",
            "self-criticism"
        ]
    },
    "Intentions & Behaviors": {
        "Seeking Support & Help": [
            "seeking guidance",
            "seeking help",
            "venting frustration",
            "seeking engagement",
            "seeking clarity",
            "seeking information",
            "seeking empathy",
            "seeking suggestions",
            "seeking support",
            "seeking assistance",
            "seeking validation",
            "seeking permission",
            "seeking forgiveness",
            "seeking solutions",
            "seeking emotional support",
            "seeking reassurance",
            "seeking alternatives",
            "seeking understanding"
        ],
        "Requests & Suggestions": [
            "suggestions",
            "request for prayer",
            "suggesting plans",
            "request for sincerity",
            "request for help",
            "suggestive language",
            "suggestions needed",
            "suggestion for activity",
            "suggestive",
            "suggestion needed",
            "seeking recommendation",
            "request for brevity",
            "suggestion",
            "suggesting solutions",
            "suggestion for intimacy",
            "request for clarification",
            "suggestion for play",
            "request for feedback",
            "request for engagement"
        ],
        "Complaints & Criticism": [
            "negative treatment",
            "complaint",
            "negative experience",
            "provocative question",
            "negative feedback",
            "defensiveness",
            "provocative suggestion",
            "provocative language",
            "aggressive intent",
            "provocation",
            "criticisms",
            "aggression",
            "defiance",
            "negative response",
            "provocative statement",
            "negative feelings",
            "mockery",
            "criticism",
            "medication criticism",
            "negative perception",
            "self-criticism",
            "provocative comment",
            "disapproval",
            "negative emotions",
            "provocative behavior",
            "criticism of selfishness",
            "mocking",
            "aggressive confrontation"
        ],
        "Affirmations & Encouragement": [
            "affirming support",
            "supportive friendship",
            "providing reassurance",
            "support",
            "supportive relationship",
            "supportive message",
            "expressing gratitude",
            "encouragement",
            "affirmation",
            "encouraging",
            "reassurance"
        ]
    },
    "Values & Ethics": {
        "Moral Values": [
            "moral struggle",
            "moral confusion",
            "self-awareness",
            "moral dilemma",
            "moral perspective",
            "moral values",
            "moral reasoning"
        ],
        "Ethical Values": [
            "ethical considerations",
            "ethical dilemma",
            "ethical values",
            "expressing concern",
            "ethical reasoning"
        ],
        "Religious & Spiritual Values": [
            "expressing doubt",
            "spirituality",
            "spiritual support",
            "religious beliefs",
            "religious devotion",
            "life philosophy",
            "spiritual reflection",
            "religious debate"
        ]
    },
    "Sexual & Explicit Content": {
        "Sexual Desires & Expressions": [
            "sexual struggles",
            "sexual intent",
            "sexual humor",
            "sexual harassment",
            "sexual intimacy discussion",
            "sexual content",
            "sexual suggestion",
            "sexual dissatisfaction",
            "sexual arousal",
            "sexual tension",
            "romantic fantasy",
            "sexual advances",
            "sexual expression",
            "sexual confidence",
            "sexual attraction",
            "sexual desire",
            "sexual",
            "sexual excitement",
            "sexual innuendo",
            "romantic confession"
        ],
        "Vulgar & Explicit Language": [
            "offensive language",
            "profanity",
            "vulgar language",
            "inappropriate humor",
            "provocative language",
            "explicit language",
            "inappropriate conversation",
            "inappropriate language",
            "vulgarity",
            "inappropriate suggestion",
            "sexually suggestive",
            "provocative behavior",
            "use of strong language",
            "explicit",
            "sexually explicit",
            "provocative comment",
            "provocative statement"
        ],
        "Sexual Relationships & Issues": [
            "sexual struggles",
            "romantic desire",
            "romantic possession",
            "romantic promise",
            "romantic flirtation",
            "romantic intent",
            "sexual harassment",
            "romantic commitment",
            "relationship turmoil",
            "infidelity",
            "romantic trust",
            "romantic affection",
            "sexual frustration",
            "expressing desire",
            "romantic relationships"
        ]
    },
    "Miscellaneous": {
        "Others": [
            "intent clarification",
            "swagger",
            "robot activities",
            "property discussion",
            "emotional honesty",
            "value of life",
            "objectification",
            "financial saving",
            "technology",
            "attachment issues",
            "property investment",
            "music interest",
            "AI",
            "personal achievements",
            "privacy concerns",
            "relational strain",
            "weather concerns",
            "texture application",
            "desire for interaction",
            "safety concerns",
            "device troubleshooting",
            "financial security",
            "data training",
            "discussion about history"
        ]
    }
}